//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drapper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yevmiye
    {
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
        public string F6 { get; set; }
        public string TL { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public string HESAP_PLANI { get; set; }
        public string F11 { get; set; }
        public Nullable<bool> F12 { get; set; }
        public int id { get; set; }
    }
}
