//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemPattern.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edefter
    {
        public string TARİH { get; set; }
        public string MADDE_NO { get; set; }
        public string FİŞ_NO { get; set; }
        public string HESAP_KODU { get; set; }
        public string HESAP_ADI { get; set; }
        public string EVRAK_NO { get; set; }
        public string EVRAK_TARİHİ { get; set; }
        public string AÇIKLAMA { get; set; }
        public Nullable<double> BORÇ { get; set; }
        public Nullable<double> ALACAK { get; set; }
        public Nullable<double> BAKİYE { get; set; }
        public string B_A { get; set; }
        public int DefterID { get; set; }
    }
}
